# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='seller',
            field=models.CharField(choices=[('P', 'Private seller'), ('D', 'Dealer')], max_length=1),
        ),
    ]
