# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20170728_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/marketplace/'),
        ),
    ]
