# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_listing_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='title', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/marketplace/images/'),
        ),
    ]
