# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20170729_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(default='city', max_length=50),
            preserve_default=False,
        ),
    ]
