# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_listing_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default='desc'),
            preserve_default=False,
        ),
    ]
