# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/marketplace/images/'),
        ),
    ]
