# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_auto_20170830_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/marketplace/images/', validators=[marketplace.models.file_size]),
        ),
    ]
