# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 11:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0026_auto_20171116_2012'),
        ('marketplace', '0010_auto_20171030_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(null=True, upload_to='static/marketplace/images/us/', validators=[marketplace.models.file_size])),
                ('price', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('year', models.IntegerField(choices=[(2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991)])),
                ('color', models.CharField(choices=[('WE', 'White'), ('BK', 'Black'), ('SR', 'Silver'), ('GY', 'Grey'), ('RD', 'Red'), ('BE', 'Blue'), ('GN', 'Green'), ('YW', 'Yellow'), ('OE', 'Orange')], max_length=2)),
                ('condition', models.CharField(choices=[('N', 'New'), ('U', 'Used')], max_length=1)),
                ('seller', models.CharField(choices=[('P', 'Private seller'), ('D', 'Dealer')], max_length=1)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.CarUS')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
