# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-20 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_listingus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/marketplace/images/<django.db.models.fields.related.ForeignKey>/', validators=[marketplace.models.file_size]),
        ),
    ]
