# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20170720_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='bore_stroke_mm',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
