# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20170720_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='rooaf_load_kg',
            new_name='roof_load_kg',
        ),
    ]
