# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20170720_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model_body_platform_years',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='model_version_description_years',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='model_platform_years',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='model_version',
            new_name='version',
        ),
    ]
