# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20170720_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='description',
            new_name='years',
        ),
    ]
