# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='baslik', max_length=50),
            preserve_default=False,
        ),
    ]
