# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 13:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 26, 13, 36, 32, 861552, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
