# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_auto_20170727_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([]),
        ),
    ]
