# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0022_auto_20170727_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created']},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('car', 'user')]),
        ),
    ]
