# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0023_auto_20170727_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
