# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/home/images/'),
        ),
    ]
