# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170830_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='opinion',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='opinion',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
