# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='followers', to='reviews.Car'),
        ),
    ]
