# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20171017_1327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilePicture',
            new_name='Profile',
        ),
    ]
