# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-14 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20171017_1327 (1)'),
        ('home', '0010_auto_20171017_1513'),
        ('home', '0009_auto_20171017_1327(1)'),
    ]

    operations = [
    ]
