# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-14 17:05
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_merge_20171114_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepicture',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='Turkey', max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
