# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-16 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0026_auto_20171116_2012'),
        ('home', '0012_auto_20171114_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='cars_us',
            field=models.ManyToManyField(blank=True, related_name='followers', to='reviews.CarUS'),
        ),
    ]
